name = "BLS381"
uuid = "ac0f3800-abd4-11e9-2e6f-fdd7b39d4d39"
authors = ["Zalan Blenessy <zalan.blenessy@gmail.com>"]
version = "0.1.0"

[deps]
RelicToolkit = "976a8074-9f4c-11e9-1019-17da4c65f546"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
